embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 4

llm:
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "stepfun/step-3.5-flash:free"
    temperature: 0
    base_url: "https://openrouter.ai/api/v1"

  ollama:
    provider: "ollama"
    base_url: "http://localhost:11434"
    model_name: "gpt-oss:120b-cloud"
    temperature: 0
    max_output_tokens: 2048
